version: '3.7'

services:
  postgres:
    image: postgres:16.3
    ports:
      - '8092:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: notes
      POSTGRES_PASSWORD: "gqaD__FuVzfJxtgXzyY1k2SybchTVCJr"
    volumes:
      - notes_data:/var/lib/postgresql/data
  redis:
    image: redis:6.2.6
    ports:
      - '8091:6379'
    command: redis-server --requirepass "z04DVbj3hw9ehbMdHAsEnxVmSMPwwrF7"
    environment:
      - REDIS_REPLICATION_MODE=master
volumes:
  notes_data:
